apiVersion: v1
kind: Service
metadata:
  name: mysql-service
  namespace: notes-app
spec:
  selector:
    app: mysql
  ports:
    - protocol: TCP
      port: 3306
      targetPort: 3306
  type: ClusterIP
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql
  namespace: notes-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mysql
  template:
    metadata:
      labels:
        app: mysql
    spec:
      containers:
        - name: mysql
          image: mysql:8.0
          env:
            - name: MYSQL_ROOT_PASSWORD
              value: mypassword   # must match DB_PASSWORD in your Django env
            - name: MYSQL_DATABASE
              value: notesdb      # must match DB_NAME in your Django env
          ports:
            - containerPort: 3306

