kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: ekram-manager
  namespace: notes-app
rules:
  - apiGroups: ["*", "apps"]
    resources: ["deployment", "pod", "service"]
    verbs: ["get", "apply","delete", "watch"]
